### ISSUE TITLE
eShop

### ISSUE THREAD

**Issue by twsouthwick** [CoreWebForms/Samples#2]
This issue is to track getting eShop working with no changes:

- [x] Special case Autofac (#1)
- [x] Static files don't seem to be served
- [x] https://github.com/CoreWebForms/CoreWebForms/issues/118
- [x] https://github.com/CoreWebForms/CoreWebForms/pull/119
- [x] https://github.com/CoreWebForms/CoreWebForms/pull/120
- [x] System.Drawing is needed - why and can it be removed? https://github.com/CoreWebForms/CoreWebForms/issues/125
- [x] Default.aspx needs to be configured for '/' https://github.com/CoreWebForms/CoreWebForms/issues/127
- [x] https://github.com/CoreWebForms/CoreWebForms/pull/126

PR to enable this is here: https://github.com/CoreWebForms/Samples/pull/1
